# Site settings
title: Troy Howard Website
description: A website on my own specialties and the interests in the field of software development 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Troy Howard
user_description: A software developer that delves into cyber security and artificial intelligence
user_title: Software Developer
email: troyhoward2000@gmail.com
github_username: thoward01


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
